server:
  port: 9129

spring:
  application:
    name: phoenix-config-server

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.200.61:3306/phoenix_config?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: phoenix
    password: Phoenix@2024
  #    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:h2db
#    username: root
#    password: 123456

#  sql:
#    init:
#      schema-locations: classpath:db.sql
#      mode: always
#  h2:
#    console:
#      enabled: true
#      path: /h2
#      settings:
#        web-allow-others: true


logging:
  level:
    root: info
    org.springframework: info
    io.github.zyszero.phoenix.config: debug