### list
GET http://localhost:9129/list?app=app1&env=dev&ns=public


### update
POST http://localhost:9129/update?app=app1&env=dev&ns=public
Content-Type: application/json

{
  "phoenix.a": "dev1888",
  "phoenix.b": "cc200",
  "phoenix.d": "dd200"
}

### version
GET http://localhost:9129/version?app=app1&env=dev&ns=public


### demo 8888
GET http://localhost:8888/demo